### ISSUE TITLE
R_CAN_RXでchごとに通信速度を設定出来ない

### ISSUE THREAD

**Issue by NoMaY-jp** [renesas/rx-driver-package#15]
こんにちは。NoMaYです。

お節介かもとも思いましたが、かふぇルネに投稿されていましたので、こちらにも投稿しておきます。

CANの通信速度について
https://japan.renesasrulz.com/cafe_rene/f/forum5/6856/can

以下の定義をチャンネル毎に用意させるよう改造することで技術的には可能ではないかと思うのです。

定義側
https://github.com/renesas/rx-driver-package/blob/153ad8704a7b9b368f53546d006d763c83799664/source/r_can_rx/r_can_rx_vx.xx/r_can_rx/ref/r_can_rx_config_reference.h#L169-L173

参照側
https://github.com/renesas/rx-driver-package/blob/153ad8704a7b9b368f53546d006d763c83799664/source/r_can_rx/r_can_rx_vx.xx/r_can_rx/src/r_can_rx.c#L1522-L1543

**Comment by HirokiIshiguro** [comment]
@NoMaY-jp さん　ありがとうございます。本件RX Driver Package開発に連絡しておきました。

**Comment by HirokiIshiguro** [comment]
@NoMaY-jp さん　本件開発チームに正式にインプットされ開発が始まりました。正式リリースは明言できませんが次版で直る見込みです。直ったらまた連絡いたします。

**Comment by HirokiIshiguro** [comment]
@NoMaY-jp 本件直りました。
RX Driver Package v130以降で直っています。https://github.com/renesas/rx-driver-package/releases/tag/V1.30
RXファミリのドライバパッケージもRAファミリに倣いGitHubでの運用が出来てきました。Issue やPull Requestの頂き方についても検討を進めています。引き続きご要望などありましたらIssueやPull Requestに送ってください。議論が必要な場合はかふぇルネに書いていただけますとこれも助かります。
