### ISSUE TITLE
R_CAN_RX V4.00にサンプルプログラムが追従出来ていない

### ISSUE THREAD

**Issue by NoMaY-jp** [renesas/rx-driver-package#16]
こんにちは。NoMaYです。

お節介かもとも思いましたが、かふぇルネに投稿されていましたので、こちらにも投稿しておきます。

CAN FITの最新ドライバ
https://japan.renesasrulz.com/cafe_rene/f/forum5/6878/can-fit/36984#36984

RX72MのCAN通信のデモサンプルプログラムについて
https://japan.renesasrulz.com/cafe_rene/f/002-2095199602/6924/rx72m-can/37274#37274

追伸

リニューアル後の かふぇルネ はログインしている時としていない時でスレッドの表示内容が変わるのかも知れません、、、(今気付いたところなので、正確な把握では無い、かも知れませんが、、、) 具体的には『RX72MのCAN通信のデモサンプルプログラムについて』の相談者さんの最後のリプライ(以下です)が、ログインしていると表示されますが、ログインしていないと表示されませんでした。
「
。。。略。。。
ご紹介頂いた内容のスレッドと全く同じ内容でした。
おかげさまで解決することが出来ました。
。。。略。。。
」

**Comment by HirokiIshiguro** [comment]
@NoMaY-jp 
本件開発チームに確認したところCAN FITモジュールのV410で直ったそうです。
他の件も追々直してまいります。
まだまだGitHub活用は実開発とのリンクが細いため活動が緩慢に見えていることかと思いますが、徐々に活動強化してまいります。
NoMaYさんのルネサスマイコンへのフィードバックに感謝いたします。
