### ISSUE TITLE
sci async sending fails if transmission is in progress

### ISSUE THREAD

**Issue by gurkerlbaron** [renesas/rx-driver-package#17]
sci fit modul in async buffered mode does not allow to send if a transmission is still in progress.
File: r_sci_rx.c

reproduce:

call R_SCI_Send with some data (data is written to internal buffer)
immediately call another R_SCI_Send (there is still some place left in buffer) 
2nd call returns with SCI_ERR_XCVR_BUSY. This is wrong

The problem is an invlaid check in sci_send_async_data.

static sci_err_t sci_send_async_data(sci_hdl_t const hdl,
                                     uint8_t         *p_src,
                                     uint16_t const  length)
{
    sci_err_t   err = SCI_SUCCESS;
    uint16_t    cnt;
    byteq_err_t byteq_err = BYTEQ_ERR_QUEUE_FULL;

    if (true != hdl->tx_idle  )
    {
        return SCI_ERR_XCVR_BUSY;
    }

#if SCI_CFG_FIFO_INCLUDED
    if (true == hdl->fifo_ctrl)

Should be replaced by

static sci_err_t sci_send_async_data(sci_hdl_t const hdl,
                                     uint8_t         *p_src,
                                     uint16_t const  length)
{
    sci_err_t   err = SCI_SUCCESS;
    uint16_t    cnt;
    byteq_err_t byteq_err = BYTEQ_ERR_QUEUE_FULL;

#if SCI_CFG_FIFO_INCLUDED
    if (true == hdl->fifo_ctrl)

**Comment by HirokiIshiguro** [comment]
@gurkerlbaron 
Thank you very much for your feedback. I will bring the answer.

**Comment by HirokiIshiguro** [comment]
@gurkerlbaron 
I have gotten following info from RX Driver Package dev team.
I will inform to this thread after fixing this issue. Thank you for your cooperation.

---
The reason of this specification is restriction of BYTEQ FIT module.
SCI FIT module uses R_BYTEQ_Put() function in BYTEQ FIT module when it put the data.
The special note of R_BYTEQ_Put() is below.
Special Notes:
If the queue is accessed at both the interrupt and application level, it is up to the user to disable and enable
the associated interrupt before and after calling this function from the application level. If the queue is
accessed by tasks of different priorities, it is up to the user to prevent task switching or to utilize a mutex or
semaphore to reserve the queue.

We are planning to update BYTEQ FIT module now.
After that, we will consider to update the current SCI FIT spec.
---

**Comment by spresg** [comment]
@gurkerlbaron 
May I know which device did you test this with?

**Comment by gurkerlbaron** [comment]
I made my tests with the RSK+RX65N-2MB kit

**Comment by gurkerlbaron** [comment]
@HirokiIshiguro 
There is the same BYTEQ interrupt problem

In methode sci_receive_async_data

R_BYTEQ_Used(hdl->u_rx_data.que, &cnt);

is called without rx interrupt disable. According to the BYTEQ documentation this is also not safe.

**Comment by HirokiIshiguro** [comment]
@gurkerlbaron Thank you for the comment. That's right. I have discussed with @sprest and RX Driver Package dev leader. We will fix this issue to receive/send both cases.
I will inform you when we would make plan to fix it.

**Comment by gurkerlbaron** [comment]
Are there any news about this issue? I think consecutive sending for a buffered async device is a main feature required.

**Comment by HirokiIshiguro** [comment]
@gurkerlbaron Thank you for your following up.
@spresg Could you inform the plan to fix this issue?

**Comment by spresg** [comment]
> @gurkerlbaron Thank you for your following up.
> @spresg Could you inform the plan to fix this issue?

Hi,
This issue has been fixed in FIT SCI_v3.80, and BYTEQ_v1.90, which are available in RDP_v1.31

**Comment by HirokiIshiguro** [comment]
@spresg Thank you very much.
@gurkerlbaron RDP v131 (includes latest SCI/ByteQ) will be available on Renesas website or GitHub.
Renesas website: https://www.renesas.com/software-tool/rx-driver-package
GitHub: https://github.com/renesas/rx-driver-package

**Comment by HirokiIshiguro** [comment]
done
