### ISSUE TITLE
USB PCDC communication device can not send data with exactly 64 bytes

### ISSUE THREAD

**Issue by gurkerlbaron** [renesas/rx-driver-package#19]
If you send exactly 64 bytes by using R_USB_Write(...), data is not sent immediatley to the usb bus. (but later on with the next write)
I used the the r_usb_pcdc middleware to send usb data. (R01AN2030EJ0130)

The problem seems to be in the r_usb_plibusbip.c Line 371

    if (g_usb_pstd_data_cnt[pipe] < (uint32_t)size)

should be replaced by 

    if (g_usb_pstd_data_cnt[pipe] <= (uint32_t)size)

In my opinion the check is wrong because if size = 64 (internal buffer size) and the data sent count is also 64 the transmission is not terminated correctly and the data is not sent. (remaining bytes is 0) In that case the bus is NOT in continuous mode.

RX65 Hardware Manual:

BVAL Bit (Buffer Memory Valid)
The BVAL bit should be set to 1 when data has been completely written to the FIFO buffer on the CPU side for the pipe 
selected using the CURPIPE[3:0] bits (selected pipe).
When the selected pipe is in the transmitting direction, set the BVAL bit to 1 in the following cases. Then, the USB 
switches the FIFO buffer from the CPU side to the SIE side, thus enabling transmission.
- To transmit a short packet, set the BVAL bit to 1 after data has been written.
- To transmit a zero-length packet, set the BVAL bit to 1 before data is written to the FIFO buffer.
When data of the maximum packet size has been written for the pipe in continuous transfer mode, the USB sets the 
BVAL bit to 1 and switches the FIFO buffer from the CPU side to the SIE side, thus enabling transmission.
Writing 1 to the BVAL bit should be done while the FRDY flag is 1 (set by the USB).
When the selected pipe is in the receiving direction, do not set the BVAL bit to 1.

This problem is reproduceable.

**Comment by HirokiIshiguro** [comment]
@gurkerlbaron 
Thank you very much, I will bring the answer.

**Comment by gurkerlbaron** [comment]
Witch layer is responsible for sending that 0 packet. How do I know on application layer about max packet size. Driver internal you know about that and hold the information e.g. USB_WRITESHRT, USB_WRITEEND.

I think the basic driver should add the zero-length packet itself if required but currently this is not done.

I found no hint about that behaviour in the driver documentation or in the PCDC sample program.

 

 

Von: TakahiroMuranaka ***@***.*** 
Gesendet: Freitag, 12. März 2021 01:22
An: renesas/rx-driver-package
Cc: gurkerlbaron; Mention
Betreff: Re: [renesas/rx-driver-package] USB PCDC communication device can not send data with exactly 64 bytes (#19)

 

Please send the zero-length packet after sending 64 bytes data.
When you sent the data of the max packet size, you need to send the zero-length packet at next packet.
(The max packet size is 64 bytes in Full-speed, 512 bytes in USB High-speed.)
In USB communication, the last packet must be the short packet. A short packet means a packet whose data size is less than the max packet size. So, If the data size is a multiple of the max packet size, then the last packet must be a zero-length packet.

**Comment by TakahiroMuranaka** [comment]
Zero length packet must be sent in the application program. Zero length packet is sent by R_USB_Write function.
Please be sure to specify USB_NULL(zero) to the 3rd argument of R_USB_Write function when sending zero-length packet.
e.g)
R_USB_Write(p_ctrl, g_buf, USB_NULL);

In additional, the max packet size is specified in USB specification.
The max packet size is 64 bytes in Full-speed, 512 bytes in High-speed.

**Comment by HirokiIshiguro** [comment]
@TakahiroMuranaka Can we close this issue? We have updated RX Driver Package to v131 now, if we still have issue related this thread, let's discussing further.

**Comment by HirokiIshiguro** [comment]
I have confirmed with @TakahiroMuranaka to close this issue. Done.
